import Logo from "@/components/ui/logo";
import "./globals.css";
import {
  Card,
  CardContent,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";

export const metadata = {
  title: "PokeFinder | by Sean and Clayton",
  description: "Generated by create next app",
  icons: [{ rel: "icon", url: "/PokeBall.png" }],
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="min-h-screen flex flex-col gap-5 justify-center items-center">
        <Logo className="scale-150 animate-bounce pt-16" />
        <Card className=" bg-red-500 border-black border-4 shadow-2xl mb-10">
          <CardContent className="h-full">{children}</CardContent>
        </Card>
      </body>
    </html>
  );
}
